// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_transmission.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_image_5ftransmission_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_image_5ftransmission_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_image_5ftransmission_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_image_5ftransmission_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_image_5ftransmission_2eproto;
class ImageTransmission;
class ImageTransmissionDefaultTypeInternal;
extern ImageTransmissionDefaultTypeInternal _ImageTransmission_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ImageTransmission* Arena::CreateMaybeMessage<::ImageTransmission>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ImageTransmission PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ImageTransmission) */ {
 public:
  inline ImageTransmission() : ImageTransmission(nullptr) {};
  virtual ~ImageTransmission();

  ImageTransmission(const ImageTransmission& from);
  ImageTransmission(ImageTransmission&& from) noexcept
    : ImageTransmission() {
    *this = ::std::move(from);
  }

  inline ImageTransmission& operator=(const ImageTransmission& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageTransmission& operator=(ImageTransmission&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ImageTransmission& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImageTransmission* internal_default_instance() {
    return reinterpret_cast<const ImageTransmission*>(
               &_ImageTransmission_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ImageTransmission& a, ImageTransmission& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageTransmission* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageTransmission* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ImageTransmission* New() const final {
    return CreateMaybeMessage<ImageTransmission>(nullptr);
  }

  ImageTransmission* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ImageTransmission>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ImageTransmission& from);
  void MergeFrom(const ImageTransmission& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageTransmission* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ImageTransmission";
  }
  protected:
  explicit ImageTransmission(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5ftransmission_2eproto);
    return ::descriptor_table_image_5ftransmission_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageDataFieldNumber = 5,
    kImageNumFieldNumber = 1,
    kWidthFieldNumber = 2,
    kHeightFieldNumber = 3,
    kChannelsFieldNumber = 4,
  };
  // bytes image_data = 5;
  void clear_image_data();
  const std::string& image_data() const;
  void set_image_data(const std::string& value);
  void set_image_data(std::string&& value);
  void set_image_data(const char* value);
  void set_image_data(const void* value, size_t size);
  std::string* mutable_image_data();
  std::string* release_image_data();
  void set_allocated_image_data(std::string* image_data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_image_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_image_data(
      std::string* image_data);
  private:
  const std::string& _internal_image_data() const;
  void _internal_set_image_data(const std::string& value);
  std::string* _internal_mutable_image_data();
  public:

  // uint32 image_num = 1;
  void clear_image_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 image_num() const;
  void set_image_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_image_num() const;
  void _internal_set_image_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 width = 2;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 height = 3;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 channels = 4;
  void clear_channels();
  ::PROTOBUF_NAMESPACE_ID::uint32 channels() const;
  void set_channels(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_channels() const;
  void _internal_set_channels(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ImageTransmission)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_data_;
  ::PROTOBUF_NAMESPACE_ID::uint32 image_num_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  ::PROTOBUF_NAMESPACE_ID::uint32 channels_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5ftransmission_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImageTransmission

// uint32 image_num = 1;
inline void ImageTransmission::clear_image_num() {
  image_num_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::_internal_image_num() const {
  return image_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::image_num() const {
  // @@protoc_insertion_point(field_get:ImageTransmission.image_num)
  return _internal_image_num();
}
inline void ImageTransmission::_internal_set_image_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  image_num_ = value;
}
inline void ImageTransmission::set_image_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_image_num(value);
  // @@protoc_insertion_point(field_set:ImageTransmission.image_num)
}

// uint32 width = 2;
inline void ImageTransmission::clear_width() {
  width_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::width() const {
  // @@protoc_insertion_point(field_get:ImageTransmission.width)
  return _internal_width();
}
inline void ImageTransmission::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  width_ = value;
}
inline void ImageTransmission::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:ImageTransmission.width)
}

// uint32 height = 3;
inline void ImageTransmission::clear_height() {
  height_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::height() const {
  // @@protoc_insertion_point(field_get:ImageTransmission.height)
  return _internal_height();
}
inline void ImageTransmission::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  height_ = value;
}
inline void ImageTransmission::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:ImageTransmission.height)
}

// uint32 channels = 4;
inline void ImageTransmission::clear_channels() {
  channels_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::_internal_channels() const {
  return channels_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ImageTransmission::channels() const {
  // @@protoc_insertion_point(field_get:ImageTransmission.channels)
  return _internal_channels();
}
inline void ImageTransmission::_internal_set_channels(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  channels_ = value;
}
inline void ImageTransmission::set_channels(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_channels(value);
  // @@protoc_insertion_point(field_set:ImageTransmission.channels)
}

// bytes image_data = 5;
inline void ImageTransmission::clear_image_data() {
  image_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ImageTransmission::image_data() const {
  // @@protoc_insertion_point(field_get:ImageTransmission.image_data)
  return _internal_image_data();
}
inline void ImageTransmission::set_image_data(const std::string& value) {
  _internal_set_image_data(value);
  // @@protoc_insertion_point(field_set:ImageTransmission.image_data)
}
inline std::string* ImageTransmission::mutable_image_data() {
  // @@protoc_insertion_point(field_mutable:ImageTransmission.image_data)
  return _internal_mutable_image_data();
}
inline const std::string& ImageTransmission::_internal_image_data() const {
  return image_data_.Get();
}
inline void ImageTransmission::_internal_set_image_data(const std::string& value) {
  
  image_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ImageTransmission::set_image_data(std::string&& value) {
  
  image_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ImageTransmission.image_data)
}
inline void ImageTransmission::set_image_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ImageTransmission.image_data)
}
inline void ImageTransmission::set_image_data(const void* value,
    size_t size) {
  
  image_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ImageTransmission.image_data)
}
inline std::string* ImageTransmission::_internal_mutable_image_data() {
  
  return image_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ImageTransmission::release_image_data() {
  // @@protoc_insertion_point(field_release:ImageTransmission.image_data)
  return image_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ImageTransmission::set_allocated_image_data(std::string* image_data) {
  if (image_data != nullptr) {
    
  } else {
    
  }
  image_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ImageTransmission.image_data)
}
inline std::string* ImageTransmission::unsafe_arena_release_image_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ImageTransmission.image_data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return image_data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ImageTransmission::unsafe_arena_set_allocated_image_data(
    std::string* image_data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (image_data != nullptr) {
    
  } else {
    
  }
  image_data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      image_data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ImageTransmission.image_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_image_5ftransmission_2eproto
